// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYnxH78EXseMKchncWISJV0TSuTkfKs9g',
    appId: '1:486550310759:web:c878590eca59859a7aa9c2',
    messagingSenderId: '486550310759',
    projectId: 'firstloginprojectbymann',
    authDomain: 'firstloginprojectbymann.firebaseapp.com',
    storageBucket: 'firstloginprojectbymann.appspot.com',
    measurementId: 'G-CQ6MSHDBFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb1Or8HjPKRTjE72xrKzP3Dn22jYqzu_E',
    appId: '1:486550310759:android:3579c3ed822e38087aa9c2',
    messagingSenderId: '486550310759',
    projectId: 'firstloginprojectbymann',
    storageBucket: 'firstloginprojectbymann.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Tl-FNKHhPN4Rs1hpB7D9kRx1B5EER0Q',
    appId: '1:486550310759:ios:e8075be913a5daba7aa9c2',
    messagingSenderId: '486550310759',
    projectId: 'firstloginprojectbymann',
    storageBucket: 'firstloginprojectbymann.appspot.com',
    iosBundleId: 'com.example.first',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Tl-FNKHhPN4Rs1hpB7D9kRx1B5EER0Q',
    appId: '1:486550310759:ios:aa98a109216481d67aa9c2',
    messagingSenderId: '486550310759',
    projectId: 'firstloginprojectbymann',
    storageBucket: 'firstloginprojectbymann.appspot.com',
    iosBundleId: 'com.example.first.RunnerTests',
  );
}
