name: "Build & Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'beta'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Format code
        run: dart format .

      - name: Analyze code
        run: flutter analyze .

      - name: Build APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}